import 'module-alias/register'
import { mongo } from '@diia-inhouse/db'
import { Env } from '@diia-inhouse/env'

import { PublicServiceCategoryStatus, PublicServiceTabCode } from '@src/generated'

const collectionName = 'publicservicecategories'

export async function up(db: mongo.Db): Promise<void> {
    const isProd = process.env.NODE_ENV === Env.Prod

    const publicServiceCategories: Record<string, unknown>[] = [
        {
            category: 'carServices',
            name: 'Водієві',
            icon: '🚗',
            status: PublicServiceCategoryStatus.active,
            sortOrder: 600,
            tabCodes: [PublicServiceTabCode.citizen],
        },
        {
            category: 'certificates',
            name: 'Довідки та витяги',
            icon: '📋',
            status: PublicServiceCategoryStatus.active,
            sortOrder: 1600,
            tabCodes: [PublicServiceTabCode.citizen],
        },
        {
            category: 'residence',
            name: 'Місце проживання',
            icon: '🏠',
            status: PublicServiceCategoryStatus.active,
            sortOrder: 700,
            tabCodes: [PublicServiceTabCode.citizen],
        },
        {
            category: 'documents',
            name: 'Замовлення документів',
            icon: '📑',
            status: PublicServiceCategoryStatus.inactive,
            sortOrder: 190,
            tabCodes: [PublicServiceTabCode.citizen],
        },
        {
            category: 'medicalServices',
            name: 'COVID-сертифікати',
            icon: '😷',
            status: PublicServiceCategoryStatus.active,
            sortOrder: 1800,
            tabCodes: [PublicServiceTabCode.citizen],
        },
        {
            category: 'payments',
            name: 'Штрафи ПДР',
            icon: '🚔',
            status: PublicServiceCategoryStatus.inactive,
            sortOrder: isProd ? 121 : 120,
            tabCodes: [PublicServiceTabCode.citizen],
        },
        {
            category: 'eDemocracy',
            name: 'Е-Демократія',
            icon: '✅',
            status: PublicServiceCategoryStatus.inactive,
            sortOrder: 150,
            tabCodes: [PublicServiceTabCode.citizen],
        },
        {
            category: 'taxServices',
            name: 'Податки',
            icon: '💼',
            status: PublicServiceCategoryStatus.active,
            sortOrder: 1100,
            tabCodes: [PublicServiceTabCode.citizen],
        },
        {
            category: 'socialPayments',
            name: 'Соціальні виплати',
            icon: '🏛',
            status: PublicServiceCategoryStatus.inactive,
            sortOrder: 180,
            tabCodes: [PublicServiceTabCode.citizen],
        },
        {
            category: 'courtServices',
            name: 'Судові послуги',
            icon: '⚖️',
            status: PublicServiceCategoryStatus.active,
            sortOrder: 1300,
            tabCodes: [PublicServiceTabCode.citizen],
        },
        {
            category: 'debts',
            name: 'Виконавчі провадження',
            icon: '🏛',
            status: PublicServiceCategoryStatus.active,
            sortOrder: 1500,
            tabCodes: [PublicServiceTabCode.citizen],
        },
        {
            category: 'poll',
            name: 'Опитування',
            icon: '💬',
            status: PublicServiceCategoryStatus.active,
            sortOrder: 800,
            tabCodes: [PublicServiceTabCode.citizen],
        },
        {
            category: 'petitions',
            name: 'Петиції',
            icon: '✅',
            status: PublicServiceCategoryStatus.inactive,
            sortOrder: 220,
            tabCodes: [PublicServiceTabCode.citizen],
        },
        {
            category: 'socialSupport',
            name: 'єПідтримка',
            icon: '😇',
            status: isProd ? PublicServiceCategoryStatus.inactive : PublicServiceCategoryStatus.active,
            sortOrder: 2000,
            tabCodes: [PublicServiceTabCode.citizen],
        },
        {
            category: 'properUser',
            name: 'Шеринг авто',
            icon: '🏁',
            status: PublicServiceCategoryStatus.active,
            sortOrder: 135,
            tabCodes: [PublicServiceTabCode.citizen],
        },
        {
            category: 'donation',
            name: 'Допомога армії',
            icon: '🇺🇦',
            status: PublicServiceCategoryStatus.active,
            sortOrder: 100,
            tabCodes: [PublicServiceTabCode.citizen],
        },
        {
            category: 'trackTogether',
            name: 'єВорог',
            icon: '⚠',
            status: PublicServiceCategoryStatus.inactive,
            sortOrder: 90,
            tabCodes: [PublicServiceTabCode.citizen],
        },
        {
            category: 'tv',
            name: 'Дія.TV',
            icon: '📺',
            status: PublicServiceCategoryStatus.active,
            sortOrder: 106,
            tabCodes: [PublicServiceTabCode.citizen],
        },
        {
            category: 'radio',
            name: 'Дія.Радіо',
            icon: '📻',
            status: PublicServiceCategoryStatus.active,
            sortOrder: 107,
            tabCodes: [PublicServiceTabCode.citizen],
        },
        {
            category: 'medicalConsultations',
            name: 'єЛікар',
            icon: '🚑',
            status: isProd ? PublicServiceCategoryStatus.inactive : PublicServiceCategoryStatus.active,
            sortOrder: 2100,
            tabCodes: [PublicServiceTabCode.citizen],
        },
        {
            category: 'games',
            name: 'Розваги',
            icon: '🎮',
            status: PublicServiceCategoryStatus.active,
            sortOrder: 1700,
            tabCodes: [PublicServiceTabCode.citizen],
        },
        {
            category: 'property',
            name: 'єВідновлення',
            icon: '🏚',
            status: PublicServiceCategoryStatus.active,
            sortOrder: 500,
            tabCodes: [PublicServiceTabCode.citizen],
        },
        {
            category: 'internallyDisplacedPersons',
            name: 'Послуги для ВПО',
            icon: '📦',
            status: PublicServiceCategoryStatus.active,
            sortOrder: 1000,
            tabCodes: [PublicServiceTabCode.citizen],
        },
        {
            category: 'unemploymentBenefits',
            name: 'Допомога по безробіттю',
            icon: '👔',
            status: PublicServiceCategoryStatus.active,
            sortOrder: 1200,
            tabCodes: [PublicServiceTabCode.citizen],
        },
        {
            category: 'ledExchange',
            name: 'Обмін лампочок',
            icon: '💡',
            status: PublicServiceCategoryStatus.active,
            sortOrder: 900,
            tabCodes: [PublicServiceTabCode.citizen],
        },
        {
            category: 'penalties',
            name: 'Штрафи',
            icon: '⚠️',
            status: PublicServiceCategoryStatus.active,
            sortOrder: 120,
            tabCodes: [PublicServiceTabCode.citizen],
        },
        {
            category: 'bonds',
            name: 'Військові облігації',
            icon: '📃',
            status: PublicServiceCategoryStatus.active,
            sortOrder: 300,
            tabCodes: [PublicServiceTabCode.citizen],
        },
        {
            category: 'officeOfficialSearch',
            name: 'Пошук колег',
            icon: '🔎',
            status: PublicServiceCategoryStatus.active,
            sortOrder: 2300,
            tabCodes: [PublicServiceTabCode.office],
        },
        {
            category: 'officeBadges',
            name: 'Бейджі',
            icon: '🏅',
            status: PublicServiceCategoryStatus.active,
            sortOrder: 2200,
            tabCodes: [PublicServiceTabCode.office],
        },
        {
            category: 'officeWorkspace',
            name: 'Воркспейс',
            icon: '👨‍💻',
            status: PublicServiceCategoryStatus.active,
            sortOrder: 95,
            tabCodes: [PublicServiceTabCode.office],
        },
        {
            category: 'officePolls',
            name: 'Опитування для колег',
            icon: '💬',
            status: PublicServiceCategoryStatus.active,
            sortOrder: 2400,
            tabCodes: [PublicServiceTabCode.office],
        },
        {
            category: 'depositGuarantee',
            name: 'Повернення вкладів',
            icon: '🏦',
            status: PublicServiceCategoryStatus.active,
            sortOrder: 1900,
            tabCodes: [PublicServiceTabCode.citizen],
        },
        {
            category: 'invincibilityPoints',
            name: isProd ? 'Незламність' : 'Пункти Незламності та укриття',
            icon: '⚡️',
            status: PublicServiceCategoryStatus.active,
            sortOrder: 200,
            tabCodes: [PublicServiceTabCode.citizen],
        },
        {
            category: 'lendingPrograms',
            name: 'єОселя',
            icon: '🏠',
            status: PublicServiceCategoryStatus.active,
            sortOrder: 1400,
            tabCodes: [PublicServiceTabCode.citizen],
        },
        {
            category: 'vehicleServices',
            name: 'Продати транспортний засіб',
            icon: '🚘',
            status: PublicServiceCategoryStatus.active,
            sortOrder: 110,
            tabCodes: [PublicServiceTabCode.citizen],
        },
        {
            category: 'EResidentPrivateEntrepreneur',
            name: 'e-Resident Entrepreneur',
            icon: '💼',
            status: isProd ? PublicServiceCategoryStatus.inactive : PublicServiceCategoryStatus.active,
            sortOrder: 501,
            tabCodes: [PublicServiceTabCode.citizen],
        },
        {
            category: 'eResidentBankAccount',
            name: 'Open Bank account',
            icon: '💳',
            status: isProd ? PublicServiceCategoryStatus.inactive : PublicServiceCategoryStatus.active,
            sortOrder: 506,
            tabCodes: [PublicServiceTabCode.citizen],
        },
        {
            category: 'eResidentStatusTermination',
            name: 'Terminate e-Resident status',
            icon: '⛔',
            status: isProd ? PublicServiceCategoryStatus.inactive : PublicServiceCategoryStatus.active,
            sortOrder: 511,
            tabCodes: [PublicServiceTabCode.citizen],
        },
    ]

    await db.collection(collectionName).insertMany(publicServiceCategories)
}

export async function down(db: mongo.Db): Promise<void> {
    await db.dropCollection(collectionName)
}
